name: "QGIS forbedringsønske"
description: "Skabelon til indberetning af QGIS ændringsønske"
title: ""
labels: []
assignees: []

body:
  # 1) Input: Virksomhed / institution
  - type: input
    id: organisation
    attributes:
      label: "Virksomhed / institution"
      description: "Hvilken virksomhed eller institution repræsenterer du?"
      placeholder: "F.eks. Aarhus Universitet eller GeoData A/S"
    validations:
      required: true

  # 2) Checkbox: Medlemskab af QGIS brugergruppen
  - type: checkboxes
    id: medlemskab
    attributes:
      label: "Medlemskab af QGIS brugergruppen"
      options:
        - label: "Jeg eller min virksomhed/institution er medlem af QGIS brugergruppen"
    validations:
      required: true

  # 3) Dropdown: Type af issue
  - type: dropdown
    id: issue_type
    attributes:
      label: "Type af issue"
      options:
        - "Fejlrettelse"
        - "Forslag til ny funktion"
        - "Generel udvikling"
    validations:
      required: true

  # 4) Tekstfelt: Beskrivelse
  - type: textarea
    id: beskrivelse
    attributes:
      label: "Beskrivelse"
      description: "Detaljeret beskrivelse af problemet eller forslag"
      placeholder: "Skriv din beskrivelse her…"
    validations:
      required: true

  # 5) Input: Links til eksisterende issues
  - type: input
    id: links
    attributes:
      label: "Links til eksisterende issues"
      description: "Evt. link til relaterede issues på QGIS’s officielle issue-tracker"
      placeholder: "https://github.com/qgis/QGIS/issues/12345"

  # 6) Tekstfelt: Yderligere oplysninger
  - type: textarea
    id: yderligere_oplysninger
    attributes:
      label: "Yderligere oplysninger"
      description: "Andre relevante detaljer, log-uddrag, miljø-specifikationer osv."
      placeholder: "Skriv yderligere oplysninger her…"
